<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Tanmay" failures="0" tests="2" name="NewDemoTestNG.timeOut" time="2.036" errors="1" timestamp="2023-11-07T13:55:32 IST" skipped="0">
  <testcase classname="NewDemoTestNG.timeOut" name="TimeOut" time="2.034">
    <error message="Method NewDemoTestNG.timeOut.TimeOut() didn&#039;t finish within the time-out 2000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method NewDemoTestNG.timeOut.TimeOut() didn't finish within the time-out 2000
at java.base@12.0.2/java.lang.Thread.sleep(Native Method)
at app//NewDemoTestNG.timeOut.TimeOut(timeOut.java:10)
at java.base@12.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@12.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base@12.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@12.0.2/java.lang.reflect.Method.invoke(Method.java:567)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@12.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@12.0.2/java.lang.Thread.run(Thread.java:835)
]]>
    </error>
  </testcase> <!-- TimeOut -->
  <testcase classname="NewDemoTestNG.timeOut" name="TimeOut2" time="0.002"/>
</testsuite> <!-- NewDemoTestNG.timeOut -->
